### ISSUE TITLE
wrong location

### ISSUE THREAD

**Issue by R2Bb1T** [Pengfei8324/chinese_license_plate_generator#3]
double yellow length=8

沪A08526D yellow True

Traceback (most recent call last):
  File "generate_plate.py", line 34, in <module>
    img = generator.generate_plate_special(label, color, double)  
  File "/workspace/mnt/storage/yangzhuo/trafficattributecode/chinese_license_plate_generator/generate_multi_plate.py", line 261, in generate_plate_special
    img_plate_model = copy_to_image_multi(img_plate_model, font_img,
  File "/workspace/mnt/storage/yangzhuo/trafficattributecode/chinese_license_plate_generator/generate_multi_plate.py", line 76, in copy_to_image_multi
    img_crop[font_img < 200, :] = [0, 0, 0]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 53 but corresponding boolean dimension is 65

**Comment by R2Bb1T** [comment]
location_xys['8_2_220']=
[[110  15 190  75]
 [250  15 330  75]
 [ 27  90  92 200]
 [107  90 172 200]
 [187  90 252 200]
 [267  90 332 200]
 [347  90 412 200]
 [427  90 492 200]],
where 492 is strange since the width is only 480.

**Comment by R2Bb1T** [comment]
sorry, I just found out the license is illegal.
